const config = require('../../config.json');

module.exports = {
    name: 'mcf',
    aliases: "mcf",
    usage: "[query]",
    description: "Automagically search stuff on Minecraft Fourm for you.",
    availableTo: "@Members",
	execute: async(message, args) => {
        var embed
        if (args.length!=0) response = ({embed:{title:"Minecraft Fourm Search", description:`https://www.minecraftforum.net/search?search=${encodeURI(args.join(" "))}`, color:config.color}})
        else response = ({embed:{title:"You are not connected yet", description:`You need to say what you want to search for! Usage: \`${prefix}search [query]\`\nGenerated by <@${message.author.id}>`}})
        return message.channel.send(response)
        .catch(error => {
            message.reply({embed:{title:'There was an error searching for that.'}});
            console.log(error)
        });
    },
};