const { prefix, color } = require('../../config.json');

module.exports = {
    name: 'search',
    aliases: "google",
    usage: "[query]",
    description: "Automagically search stuff on google for you.",
    availableTo: "@Members",
	execute: async(message, args) => {
        var embed
        if (args.length!=0) response = ({embed:{title:"Google Search", description:`https://letmegooglethat.com/?q=${encodeURI(args.join(" "))}`, color:color}})
        else response = ({embed:{title:"You are not connected yet", description:`You need to say what you want to search for! Usage: \`${prefix}search [query]\`\nGenerated by <@${message.author.id}>`}})
        return message.channel.send(response)
        .catch(error => {
            message.reply({embed:{title:'There was an error searching for that.'}});
        });
    },
};